using QMgr.Domain.Common;

namespace QMgr.Domain.Entities.Identity;

/// <summary>
/// One signed-in device. The row behind "keep me signed in" on the mobile app.
///
/// <para><b>Why this is a table and not a column, against this project's standing
/// enhance-before-add rule.</b> Q-Mgr already had a refresh token:
/// <c>User.RefreshToken</c>, a single nullable string. One column cannot hold N devices, and
/// the consequences of trying were not theoretical — a phone signing in replaced the value and
/// so evicted the browser, the browser refreshing evicted the phone, and there was nothing to
/// revoke ONE lost handset with. That is the constraint's own
/// "sub-resource with an independent lifecycle an existing row cannot represent no matter how
/// many columns it grows" clause, the same one <c>WelfareAttachment</c> was allowed under.</para>
///
/// <para><b><see cref="User.RefreshToken"/> deliberately stays and is untouched.</b> It is what
/// the Blazor web signs in with. Migrating the browser onto this table has a blast radius across
/// every signed-in tab, and folding that into a mobile change is how one feature takes out
/// another.</para>
///
/// <para><b>Four security properties, and they are behaviour rather than implementation
/// detail.</b> RFC 9700 §4.14 requires the second of them outright for a public client, which a
/// mobile app is:</para>
/// <list type="number">
///   <item><b>Only a hash is stored</b> (<see cref="TokenHash"/>), so a database copy yields no
///     usable credential.</item>
///   <item><b>Rotated on every redeem</b>, so a stolen token works at most once — and its reuse
///     is DETECTABLE, because the legitimate device's next refresh then fails the hash check and
///     the whole device session is revoked.</item>
///   <item><b>Bound to the credential version</b> (<see cref="CredentialStamp"/>), so a password
///     change kills every device without hunting for rows.</item>
///   <item><b>The token carries its own identity</b> — <c>{userId}.{deviceId}.{secret}</c> — so
///     validating it is one keyed lookup rather than a scan across every user's tokens. That is
///     also the bug the web side still has: <c>User.RefreshToken</c> is matched by an unindexed
///     equality scan over the whole table.</item>
/// </list>
/// </summary>
public class UserDeviceSession : BaseAuditableEntity
{
    public Guid UserId { get; set; }
    public User? User { get; set; }

    /// <summary>
    /// The organisation, denormalised from the user so the tenant purge can reach these rows by
    /// the shortest FK path and so a per-tenant count needs no join. <c>TenantPurgeModel</c>
    /// walks the model for exactly this column.
    /// </summary>
    public Guid OrganizationId { get; set; }

    /// <summary>
    /// The device's own id, generated by the app and stable across sign-ins on that handset.
    /// Constrained to a safe alphabet by <c>DeviceSessionService.NormaliseDeviceId</c> because it
    /// travels inside the dotted token, where a '.' would shift every field boundary.
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>What the user will recognise in a device list — "Samsung SM-A155F".</summary>
    public string? DeviceName { get; set; }

    /// <summary>android · ios · windows. Decides whether an update can self-install.</summary>
    public string? Platform { get; set; }

    public string? AppVersion { get; set; }
    public long AppVersionCode { get; set; }

    /// <summary>
    /// SHA-256 of the current secret, base64. Compared in fixed time — a length-independent
    /// equality check here would leak the hash a byte at a time.
    /// </summary>
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>
    /// A copy of <see cref="User.CredentialStamp"/> as it was when this token was last issued.
    /// A password change rolls the user's stamp, so every device's copy stops matching and every
    /// device is signed out on its next refresh. This is the kill switch, and it is why the stamp
    /// has to be written by EVERY path that changes a password — one missed writer is a password
    /// change that does not sign the phone out.
    /// </summary>
    public string? CredentialStamp { get; set; }

    public DateTime IssuedAt { get; set; }
    public DateTime LastUsedAt { get; set; }
    public DateTime ExpiresAt { get; set; }

    /// <summary>Set when revoked. The row is KEPT so "what happened to my session" has an answer.</summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>Why it was revoked — signed out, replaced, replayed, credentials changed.</summary>
    public string? RevokedReason { get; set; }

    // ── Push ────────────────────────────────────────────────────────────────────────────
    //
    // The push token lives on the DEVICE row rather than on the user, because that is what it
    // identifies. A user with three handsets has three tokens and a notification goes to all of
    // them; a user whose phone was wiped has one dead token and two live ones.

    /// <summary>The FCM registration token, or null when the app has none yet.</summary>
    public string? PushToken { get; set; }

    /// <summary>
    /// Whether the OS will actually DISPLAY a notification. A device can hold a perfectly good
    /// token and show nothing because the user declined the Android 13 permission, and a fleet
    /// that cannot tell those apart cannot explain why a broadcast "delivered" to a silent
    /// handset. Both halves are needed before anything is sent.
    /// </summary>
    public bool PushPermitted { get; set; }

    public DateTime? PushTokenUpdatedAt { get; set; }

    /// <summary>
    /// Set when FCM answers that this token is gone (UNREGISTERED / INVALID_ARGUMENT). The token
    /// is cleared rather than the row deleted: the SESSION may still be perfectly live, and
    /// deleting it would sign somebody out because their notifications stopped working.
    /// </summary>
    public DateTime? PushFailedAt { get; set; }

    public DateTime? LastCheckInAt { get; set; }

    /// <summary>True when this session can be redeemed right now.</summary>
    public bool IsLive => RevokedAt == null && ExpiresAt > DateTime.UtcNow;

    /// <summary>True when a notification sent to this device would actually be shown.</summary>
    public bool CanReceivePush =>
        IsLive && PushPermitted && !string.IsNullOrWhiteSpace(PushToken) && PushFailedAt == null;
}
